swagger: "2.0"
info:
  title: DBadger API
  description: Documentation of DBadger REST API.
  version: 1.0.0
host: localhost:8080
basePath: /connections
schemes:
  - http
paths:
  /:
    get:
      summary: Returns an array of db connections.
      tags:
        - Connection
      produces:
        - application/json
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Connection"
    post:
      summary: Creates new db connection.
      tags:
        - Connection
      consumes:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "DB Connection to be created."
          required: true
          schema:
            allOf:
              - $ref: "#/definitions/Connection"
            required:
              - hostname
              - databaseName
              - username
      responses:
        '200':
          description: Created.
        '400':
          description: Bad request.
        '409':
          description: Connection with provided id already exists.
    put:
      summary: Updates db connection.
      tags:
        - Connection
      consumes:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "DB Connection to be created."
          required: true
          schema:
            allOf:
              - $ref: "#/definitions/Connection"
            required:
              - id
              - hostname
              - databaseName
              - username
      responses:
        '200':
          description: Updated.
        '400':
          description: Bad request.
        '404':
          description: Connection was not found.
  /{id}:
    get:
      summary: Returns a db connection.
      tags:
        - Connection
      produces:
        - application/json
      parameters:
        - name: "id"
          in: "path"
          description: "The id of db connection."
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Connection"
        '400':
          description: Bad request.
        '404':
          description: Connection  was not found.
    delete:
      summary: "Deletes db connection."
      tags:
        - Connection
      parameters:
        - name: "id"
          in: "path"
          description: "The id of db connection that needs to be deleted."
          required: true
          type: "string"
      responses:
        '200':
          description: Deleted.
        '400':
          description: Bad request.
        '404':
          description: Connection was not found.
  /{id}/metadata/schemas:
    get:
      summary: Returns a list of db schemas.
      tags:
        - Metadata
      produces:
        - application/json
      parameters:
        - name: "id"
          in: "path"
          description: "The id of db connection."
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Schema"
        '400':
          description: Bad request.
        '404':
          description: Connection was not found.
definitions:
  Connection:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 12
      name:
        type: "string"
        example: "library"
      hostname:
        type: "string"
        example: "localhost"
      port:
        type: "integer"
        format: "int32"
        example: 5432
      databaseName:
        type: "string"
        example: "db_library"
      username:
        type: "string"
        example: "library_admin"
      password:
        type: "string"
        example: "library_admin"
  Schema:
    type: "object"
    properties:
      name:
        type: "string"
        example: "library"
      owner:
        type: "string"
        example: "localhost"
