version: '3.9'
services:
  db:
    build: psql/.
    image: ataccama/dbadger-psql
    command: postgres -c 'max_connections=700'
    environment:
      - POSTGRES_DB=dbadger
      - POSTGRES_USER=dbr_admin
      - POSTGRES_PASSWORD=dbr_admin
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d dbadger -U dbr_admin"]
      interval: 5s
      start_period: 5s
networks:
  default:
    name: dbadger_network
